---
- name: Install pypatcher
  hosts: pypatcher
  become: yes
  vars_files:
  - vars/default.yml

  tasks:
    - name: Install dependencies
      apt:
        pkg:
        - jackd
        - libjack-jackd2-dev
        - mpg123
        - python3-pip
        - darkice
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Configure jackd realtime priority
      command: cp /etc/security/limits.d/audio.conf.disabled /etc/security/limits.d/audio.conf

    - name: Create pypatcher_deps container
      command: docker create sandreae/pypatcher_deps:latest
      register: container_id

    - name: Copy dependencies from container
      command: docker cp {{ container_id.stdout}}:build/. /usr/local/bin/

    - name: Fetch lounge-music
      get_url:
        url: "{{ lounge_music_url }}"
        dest: /home/{{user}}/lounge-music.mp3
        mode: '0440'
  
    - name: Template and send darkice.cfg
      template:
        src: templates/darkice.cfg.j2
        dest: /etc/darkice.cfg

    - name: Git checkout jacktrip_pypatcher
      git:
        repo: 'https://github.com/noiseorchestra/jacktrip_pypatcher'
        dest: /home/{{user}}/jacktrip_pypatcher
        version: 2.0.0

    - name: Install pypatcher python dependencies
      command: python3 -m pip install -r /home/{{user}}/jacktrip_pypatcher/requirements.txt

    - name: Copy service files
      copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/"
      with_fileglob:
        - "services/*.service"      
        
    - name: Install systemd config
      copy:
        src: "{{ item }}"
        dest: "/etc/systemd/"
      with_fileglob:
        - "templates/*.conf"  
        
    - name: Make jacktrip_pypatcher config folder
      command: mkdir -p /etc/jacktrip_pypatcher

    - name: Copy py_patcher config files
      copy:
        src: "{{ item }}"
        dest: "/etc/jacktrip_pypatcher/"
      with_fileglob:
        - "services/config/*.conf"      

    - name: Start services
      command: "{{ item }}"
      with_items:
      - systemctl start jackd.service
      - systemctl start jacktrip.service
      - systemctl start pypatcher_darkice.service
      - systemctl start pypatcher_callback.service
      - systemctl start pypatcher_watchgod.service

    - name: Enable services
      command: "{{ item }}"
      with_items:
      - systemctl enable jackd.service
      - systemctl enable jacktrip.service
      - systemctl enable pypatcher_darkice.service
      - systemctl enable pypatcher_callback.service
      - systemctl enable pypatcher_watchgod.service
