---
user: jacktrip
pypatcher_version: replace-sam-user
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'apt-transport-https', 'ca-certificates', 'curl', 'git', 'software-properties-common', 'ufw' ]